### ISSUE TITLE
Upgrade to Node 4.x and latest libraries

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#115]
Currently juice-shop only works with 0.10.x, preferrably a version >=0.10.28 to be on the safe side. With 0.11 and 0.12 there are problems with running tests originating from at least `sequelize`:

```
/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/utils/parameter-validator.js:76
    var _value       = (value === null) ? 'null' : value.toString()
                                                         ^
TypeError: undefined is not a function
    at validate (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/utils/parameter-validator.js:76:58)
    at Object.module.exports.check (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/utils/parameter-validator.js:30:10)
    at Object.module.exports.validateParameter (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/utils.js:580:31)
    at module.exports.DAOFactory.create (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize/lib/dao-factory.js:688:11)
    at handleResourceCreate (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize-restful/lib/router.js:324:8)
    at Router.handleRequest (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize-restful/lib/router.js:67:34)
    at /home/travis/build/bkimminich/juice-shop/node_modules/sequelize-restful/lib/index.js:10:16
    at /home/travis/build/bkimminich/juice-shop/node_modules/sequelize-restful/node_modules/connect/lib/middleware/bodyParser.js:56:25
    at IncomingMessage.<anonymous> (/home/travis/build/bkimminich/juice-shop/node_modules/sequelize-restful/node_modules/connect/lib/middleware/urlencoded.js:73:11)
    at IncomingMessage.emit (events.js:104:17)
npm ERR! Test failed.  See above for more details.
```
